apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - image: okteto.dev/guestbook:latest
        name: guestbook

---

apiVersion: v1
kind: Service
metadata:
  name: guestbook
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP
  ports:
  - name: "guestbook"
    port: 8080
  selector:
    app: guestbook